export const POST_FIND_ALL_START = 'POST_FIND_ALL_START';
export const POST_FIND_ALL_OK = 'POST_FIND_ALL_OK';
export const POST_FIND_ALL_NOK = 'POST_FIND_ALL_NOK';

export const POST_FIND_BY_ID_START = 'POST_FIND_BY_ID_START';
export const POST_FIND_BY_ID_OK = 'POST_FIND_BY_ID_OK';
export const POST_FIND_BY_ID_NOK = 'POST_FIND_BY_ID_NOK';

export const POST_SAVE_START = 'POST_SAVE_START';
export const POST_SAVE_OK = 'POST_SAVE_OK';
export const POST_SAVE_NOK = 'POST_SAVE_NOK';
export const POST_SAVE_VOID = 'POST_SAVE_VOID';

export const POST_UPDATE_START = 'POST_UPDATE_START';
export const POST_UPDATE_OK = 'POST_UPDATE_OK';
export const POST_UPDATE_NOK = 'POST_UPDATE_NOK';
export const POST_UPDATE_VOID = 'POST_UPDATE_VOID';

export const POST_DELETE_START = 'POST_DELETE_START';
export const POST_DELETE_OK = 'POST_DELETE_OK';
export const POST_DELETE_NOK = 'POST_DELETE_NOK';
export const POST_DELETE_VOID = 'POST_DELETE_VOID';